version: '1'

services:
  # TODO: Add backend-service for local development
  # tkart-backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #   - 3000:3000
  #   env_file: .env
  #   depends_on:
  #     - mongo
  #   networks:
  #     - dev-network

  mongo:
    image: mongo:5.0.6
    container_name: mongo-dev
    restart: always
    networks:
      - dev-network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"

networks:
  dev-network:
    driver: bridge
