version: '1'

services:
  mongo:
    image: mongo:5.0.6-alpine
    container_name: mongo-dev
    restart: always
    networks:
      - dev-network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"

networks:
  dev-network:
    driver: bridge
    