version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - .:/app
    ports:
    - 3000:3000
    env_file: .env
    depends_on:
      - mongo
    networks:
      - dev-network
    command: npm run start:dev

  mongo:
    image: mongo:5.0.6
    restart: always
    networks:
      - dev-network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"

networks:
  dev-network:
    driver: bridge
